Updated the icons for the plex, region, and CICS profile
zowe/cics-for-zowe-client pull request #161
Opened 2024-12-10 11:25 UTC by Rajat-Sahrawat

6 icons for CICS profile (connected, disconnected, unverified) - light and dark
4 icons for region (connected, disconnected)- light and dark
2 for plex- light and dark

2024-12-10 19:32 UTC, davenice requested changes
hey @Rajat-Sahrawat - thanks for these! we'll need to get your commits signed (that's the DCO check) - we can work together on that.

i think we should aim to keep them 150px square like the originals - how feasible is it to do that?

Here are some screenshots of what they look like within the GUI:
<img width="80" alt="image" src="https://github.com/user-attachments/assets/12884e6e-7b4e-4d38-894d-8145303343ec">

<img width="99" alt="image" src="https://github.com/user-attachments/assets/594f14f8-237a-49b6-9ac5-c89155c2fe27">

<img width="141" alt="image" src="https://github.com/user-attachments/assets/2d4fc2d4-cf7a-41e3-9891-cb3b576c3699">

I think these look good - I like the plex and region icons especially.

@Joe-Winchester might have thoughts too!

2024-12-10 19:32 UTC, davenice commented on packages/vsce/resources/imgs/profile-dark.svg
this icon is 162px x 150px - can we keep it square?

2024-12-10 19:37 UTC, davenice commented
on reflection - before asking @Rajat-Sahrawat to fiddle around with the aspect ratios... @JillieBeanSim / @zFernand0 i see you've been requested to review - is there any requirement to stick with square? it appeals to my sense of tidiness, but.... :-)

2024-12-11 14:29 UTC, Rajat-Sahrawat commented on packages/vsce/resources/imgs/profile-dark.svg
Changed all the icons to 300x300 px

2024-12-11 14:36 UTC, Rajat-Sahrawat commented
fixed some size issues, signed and updated. @zFernand0 @JillieBeanSim ready for review now

2024-12-12 14:09 UTC, Rajat-Sahrawat commented
@zFernand0 @JillieBeanSim Let me know if I need to update the change log for the new icons

2024-12-12 14:42 UTC, zFernand0 approved these changes
The new icons look great! 🙏 
Thanks @Rajat-Sahrawat 
And thanks @davenice  for posting pictures of them 🙏

2024-12-12 14:56 UTC, merged