Have made the region name optional on the getResource SDK method
zowe/cics-for-zowe-client pull request #164
Opened 2024-12-11 12:27 UTC by enamkhan

**What It Does**
Have changed the getResource method making the region name option so we can now use this method to fetch both regions and plexes.

**How to Test**
Connect to a cicsplex and expand regions, have also added unit tests.

**Review Checklist**
I certify that I have:
- [ ] tested my changes
- [ ] added/updated automated tests
- [ ] updated the changelog
- [ ] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

2024-12-13 10:11 UTC, AndrewTwydell commented on packages/sdk/CHANGELOG.md
> +- Enhancement: Have made the region name optional on the getResource SDK method. [#164](https://github.com/zowe/cics-for-zowe-client/pull/164)
```suggestion
- Enhancement: Made the region name optional on the getResource SDK method. [#164](https://github.com/zowe/cics-for-zowe-client/pull/164)
```

2024-12-13 15:07 UTC, zFernand0 requested changes
LGTM! 😋 
Left a few comments for your consideration! 🙏 

Overall, I love what you'd done with the SDK 🙏

2024-12-13 17:56 UTC, enamkhan commented on packages/sdk/src/methods/common/Common.ts
> +export function getResourceUri(cicsPlexName: string, regionName: string, resourceName: string, criteria?: string, parameter?: string) {
Have added both the interface and class.

2024-12-14 09:18 UTC, AndrewTwydell approved these changes
Looks good 🙂

2024-12-14 09:24 UTC, AndrewTwydell requested changes
Ah just the changelog link! 🙂
https://github.com/zowe/cics-for-zowe-client/pull/164#discussion_r1883690762

2024-12-16 10:11 UTC, AndrewTwydell approved these changes
Great thanks for those @enamkhan!

2024-12-16 12:01 UTC, AndrewTwydell approved these changes

2024-12-16 18:49 UTC, zFernand0 commented on packages/sdk/src/methods/add-to-list/AddToList.ts
> +    "criteria": `NAME=='${parms.name}'`
Not a required change, but as a style recommendation (and to save a few extra key strokes... you can avoid the quotes in objects (as long as there are no special characters in the property/key name 😋 
```suggestion
    cicsPlex: parms.cicsPlex,
    regionName: parms.regionName,
    criteria: `NAME=='${parms.name}'`
```

2024-12-16 22:18 UTC, zFernand0 approved these changes
LGTM! 😋

2024-12-16 22:18 UTC, merged